### ISSUE TITLE
Can you give your include files as well?

### ISSUE THREAD

**Issue by Cruze03** [shanapu/MyStore#1]
colors.inc have old syntax so I have errors compiling this so can you upload all your include files too?

Thank you for this <3 Features are hot asf! <3 Will try to make PRs if I have suggestions!

**Comment by shanapu** [comment]
added.

I lost track of all the different chat color include out there... So if you have a better suggestion, I'm open for it.

**Please note that you should not use this store on productive servers.**
Some of the features are rather a concept than a useful extension. I've been coding the plugin over and over again the last years without much testing. The plugin was never used on a public server and tested with a maximum of 3 real players but mostly with bots.  
I also lost track of all the changes & differences to the original zeypstore and [Kxnrl](https://github.com/Kxnrl/Store) remake. So, good luck & thank you. =)

**Comment by Cruze03** [comment]
Yup sure I was gonna test it in my test server.
Thank you so much for your hardwork!!
