### ISSUE TITLE
Lootboxes disappear.

### ISSUE THREAD

**Issue by InVictus21** [shanapu/MyStore#3]
When you use a lootbox and it spawns another player can knife/shoot it to brake it. When this happens the loot doesn't drop and after a minute or so of the box being just a model (not being to touch/climb on it anymore) it disappears. 

To reproduce:
1. Spawn a lootbox.
2. When it stops spinning show another player where it is (by jumping on it or smth).
3. Another player shoots/knifes it till the hitbox disappears.

**Comment by shanapu** [comment]
Thanks for the report!
Lootboxes need a bigger rewrite. Other players will see the boxes in further but cant damage or open them. Boxes will auto-open without any action.

**Comment by shanapu** [comment]
please test update for glitches or any other abuses. Thank you!
+ added a new convar `"mystore_lootbox_visible_for_all", "1", "1 - the lootbox is visible for all player / 0 - the lootbox is only visible for player who owns it."`.  
+ removed the pickupsound convar `"mystore_lootbox_sound_pickup"` and moved sound file to items.txt "sound"-key  
+ lootbox is now nonsolid.

**Comment by shanapu** [comment]
I think the issue under this topic can be closed.
