### ISSUE TITLE
Lootboxes are only visible to the player that used it.

### ISSUE THREAD

**Issue by InVictus21** [shanapu/MyStore#4]
When a player uses a lootbox and it appears it is invisible for other people. The other people can still see the lights from the lootbox, hear the sound and climb on top of it.

**Comment by shanapu** [comment]
Thanks for the report!
Lootboxes becomes a bigger rewrite. I will show the boxes and effect to all players and restrict climbing on them.

**Comment by shanapu** [comment]
please test update for glitches or any other abuses. Thank you!
added a new convar `"mystore_lootbox_visible_for_all", "1", "1 - the lootbox is visible for all player / 0 - the lootbox is only visible for player who owns it."`.  
removed the pickupsound convar `"mystore_lootbox_sound_pickup"` and moved sound file to items.txt "sound"-key  
lootbox is now nonsolid.

**Comment by shanapu** [comment]
I think the issue under this topic can be closed.
