### ISSUE TITLE
Im not getting any credits after a few mapchanges

### ISSUE THREAD

**Issue by Exci556** [shanapu/MyStore#6]
I had around 4-6 players on the server and after a few mapchanges  we stopped getting  any credits from the store. Also included my earnings.txt.
And sorry for my poor english.
[earnings.txt](https://github.com/shanapu/MyStore/files/3557427/earnings.txt)

**Comment by shanapu** [comment]
Hi Thanks for the report!
I was able to find a bug that stops earnings when "bot_quota" is greater than 0, even if no bot is ingame.
I realy hope you had "bot_quota" "2" or something otherwise, I have to take a closer look.

I assume there where no errors in logfiles?!

**Comment by Exci556** [comment]
I found it, i guess.  After 1-2 mapchanges we need atleast 6 players to earn credits again. Kinda weird but i hope that helps!

**Comment by Exci556** [comment]
Looks like the requed player number is multiplying after every mapchange. We got above 10 players and nothing :(

**Comment by shanapu** [comment]
Did you use/test the latest version I uploaded 10hours ago?

**Comment by shanapu** [comment]
Do you have convar "bot_quota" greater than zero?

**Comment by Exci556** [comment]
My "bot_quota" was 0 the whole time, and sorry i didnt see that you updated the earnings, we testing it right now and working so far. You are amazing ^^

**Comment by Exci556** [comment]
After 2 hours of testing it stops again.

**Comment by shanapu** [comment]
After many unsuccessful tries to reproduce this, and some talks to other server operators which use mystore and don't have any of this issues, I going to close this.

_Based on your attached log, you and your server got some more serious problems. 
I recommend to setup a clean server with only sourcemod and mystore. 
When everything works well, add plugins to your needs one by one. Test and check logs and see if any issue comes with a new plugin._ 

**If you encounter a bug again, have a look at the [FAQ](https://github.com/shanapu/MyStore/wiki/FAQ), the [wiki](https://github.com/shanapu/MyStore/wiki/) or create a new issue. But you have to stick to the [template](https://github.com/shanapu/MyStore/issues/new?assignees=shanapu&labels=bug&template=bug_report.md&title=%5BBUG%5D+) for the report and give all necessary and requested information.**

**Comment by penalte** [comment]
i also have this in my servers, it happens randomly in all my 9 servers, i use bot_quota fix that adds and removes bots depending on the occasion.
