### ISSUE TITLE
Levitating weapons

### ISSUE THREAD

**Issue by Exci556** [shanapu/MyStore#7]
Since we have this store some players have their weapons levitating 15-20 meters away and moves with them. I cant recreate this bug it just happens sometimes. Attached a screenshot it might help.
![20190830125606_1](https://user-images.githubusercontent.com/54616178/64019529-ab56ba80-cb2f-11e9-9336-4bfc5af603e7.jpg)

**Comment by shanapu** [comment]
After many unsuccessful tries to reproduce this, and some talks to other server operators which use mystore and don't have any of this issues, I going to close this.

I assume comes from another plugins, a conflict with mystore or bad server.

**If you encounter a bug again, have a look at the [FAQ](https://github.com/shanapu/MyStore/wiki/FAQ), the [wiki](https://github.com/shanapu/MyStore/wiki/) or create a new issue. But you have to stick to the [template](https://github.com/shanapu/MyStore/issues/new?assignees=shanapu&labels=bug&template=bug_report.md&title=%5BBUG%5D+) for the report and give all necessary and requested information.**
